version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      PORT: 8000
      MONGODB_URL: mongodb+srv://quocan142536:Ta123456@cluster0.emuywiy.mongodb.net/nestjs-basic?retryWrites=true&w=majority
      JWT_SECRET: asfasdasfsdgsdfdsgdsg
      JWT_EXPIRES_IN: 600000
      JWT_REFRESH_SECRET: jkjdaskjk123kaja32312askjkda
      JWT_REFRESH_EXPIRES_IN: 365d
      EMAIL_USER: quocan142536@gmail.com
      EMAIL_PASSWORD: dolc dmtp axyf ftfw
      EMAIL_HOST: smtp.gmail.com
      CLOUD_NAME: diieofzuv
      API_KEY: "857436649758796"
      API_SECRET: 4U7iebWFs_oFxX_JuvCAAeOpi3c
